package presentation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import domini.SolutionDomainController;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * Class that controls the view of the modification of a solution
 * @author Rubén
 */
public class ModifySolutionView extends javax.swing.JPanel {

    private PresentationController iPresentationController;

    /**
     * Creates new form NewJPanel
     */
    public ModifySolutionView() {
        initComponents();
    }

    public ModifySolutionView(PresentationController pPresentationController, String id) {
        selectedSolutionId = id;
        initComponents();
        iPresentationController = pPresentationController;
    }

    public void setSelectedSolutionId(String selectedSolutionId) {
        this.selectedSolutionId = selectedSolutionId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        modificarSolucioTitleLabel = new javax.swing.JLabel();
        tornarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        comunitatOrigenList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        categoriesComunitatList = new javax.swing.JList();
        comunitatDestiLabel = new javax.swing.JLabel();
        categoriesComunitatLabel = new javax.swing.JLabel();
        comunitatOrigenLabel = new javax.swing.JLabel();
        moureCategoriaBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        comunitatDestiList = new javax.swing.JList();

        modificarSolucioTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        modificarSolucioTitleLabel.setText("Modificar Solució : " + selectedSolutionId);

        tornarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tornarButton.setText("Tornar");
        tornarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarButtonActionPerformed(evt);
            }
        });

        comunitatOrigenList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DefaultListModel model = new DefaultListModel();
        SolutionDomainController.setSolution(SolutionDomainController.loadSolution(selectedSolutionId));
        for (int i = 0; i < SolutionDomainController.getNumSolutionCommunities(); ++i) model.addElement("Comunitat "+i);
        comunitatOrigenList.setModel(model);
        jScrollPane2.setViewportView(comunitatOrigenList);

        categoriesComunitatList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SolutionDomainController.setSolution(SolutionDomainController.loadSolution(selectedSolutionId));
        comunitatOrigenList.setModel(model);
        jScrollPane3.setViewportView(categoriesComunitatList);

        comunitatDestiLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comunitatDestiLabel.setText("Comunitat destí");

        categoriesComunitatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoriesComunitatLabel.setText("Categories de la Comunitat ");

        comunitatOrigenLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comunitatOrigenLabel.setText("Comunitat ");

        moureCategoriaBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moureCategoriaBtn.setText("Moure Categoria");
        moureCategoriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moureCategoriaBtnActionPerformed(evt);
            }
        });

        comunitatDestiList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane5.setViewportView(comunitatDestiList);


        ListSelectionListener listSelectionListener = new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                try {
                    //fem que la comunitat desti siguin totes menys la que ja esta seleccionada
                    String community = comunitatOrigenList.getSelectedValue().toString();

                    SolutionDomainController.setSolution(SolutionDomainController.loadSolution(selectedSolutionId));
                    DefaultListModel model = new DefaultListModel();
                    for (int i = 0; i < SolutionDomainController.getNumSolutionCommunities(); ++i) {
                        String com = "Comunitat " + i;
                        if (!com.equals(community)) model.addElement(com);
                    }
                    comunitatDestiList.setModel(model);
                    int selected = Integer.valueOf(comunitatOrigenList.getSelectedValue().toString().substring(10));
                    //int selected = Integer.valueOf(community.substring(10));
                    DefaultListModel model2 = new DefaultListModel();
                    for (String s : SolutionDomainController.getSolutionNameCommunities().get(selected)) model2.addElement(s);
                    //for (Node n : SolutionDomainController.getSolutionCommunities().get(selected).getCommunity()) model2.addElement(n.getId());
                    categoriesComunitatList.setModel(model2);
                } catch (Exception e) {

                }
            }
        };
        comunitatOrigenList.addListSelectionListener(listSelectionListener);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tornarButton)
                                                        .addComponent(modificarSolucioTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(192, 192, 192)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(moureCategoriaBtn)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(81, 81, 81))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(comunitatOrigenLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGap(32, 32, 32)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(categoriesComunitatLabel)
                                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(113, 113, 113)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(comunitatDestiLabel))))))
                                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modificarSolucioTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(comunitatDestiLabel)
                                        .addComponent(categoriesComunitatLabel)
                                        .addComponent(comunitatOrigenLabel))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane5)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(moureCategoriaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(tornarButton)
                                .addGap(38, 38, 38))
        );
    }// </editor-fold>

    private void moureCategoriaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         try {
            int com_org = Integer.valueOf(comunitatOrigenList.getSelectedValue().toString().substring(10));
            int com_dest = Integer.valueOf(comunitatDestiList.getSelectedValue().toString().substring(10));
            String node = categoriesComunitatList.getSelectedValue().toString();
            SolutionDomainController.addCategory(node, com_dest);
            SolutionDomainController.removeCat(node, com_org);
            SolutionDomainController.deleteSolution(selectedSolutionId);
            SolutionDomainController.saveSolution(SolutionDomainController.getSolution());
            JOptionPane.showMessageDialog(null, "Categoria " + node + " moguda", "Moviment realitzat", JOptionPane.INFORMATION_MESSAGE);
            DefaultListModel model3 = new DefaultListModel();
            SolutionDomainController.setSolution(SolutionDomainController.loadSolution(selectedSolutionId));
            for (int i = 0; i < SolutionDomainController.getNumSolutionCommunities(); ++i) model3.addElement("Comunitat "+i);
            comunitatOrigenList.setModel(model3);
             //buidem llista de categories i comunitats
            DefaultListModel model4 = new DefaultListModel(); categoriesComunitatList.setModel(model4);
             DefaultListModel model5 = new DefaultListModel(); comunitatDestiList.setModel(model5);
         } catch (Exception e) {

        }
    }

    private void tornarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        iPresentationController.synToConsultSolutionView();
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel categoriesComunitatLabel;
    private javax.swing.JList categoriesComunitatList;
    private javax.swing.JLabel comunitatDestiLabel;
    private javax.swing.JList comunitatDestiList;
    private javax.swing.JLabel comunitatOrigenLabel;
    private javax.swing.JList comunitatOrigenList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel modificarSolucioTitleLabel;
    private javax.swing.JButton moureCategoriaBtn;
    private javax.swing.JButton tornarButton;
    private String selectedSolutionId;
    // End of variables declaration
}

