package presentation;


import domini.WikipediaDomainController;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *  Panel containing the elements of the view needed too find a solution from the current wiki.
 * @author pau
 */
public class SearchPanel extends javax.swing.JPanel {

    private PresentationController presentationController;
    private WikipediaDomainController wikiCtrl;

    /**
     * Creates new form NewJPanel
     */
    public SearchPanel(PresentationController presentationController) {
        this.presentationController = presentationController;
        this.wikiCtrl = presentationController.getWikiCtrl();
        initComponents();
        initComponents2();
    }

    /**
     * Initialize the components not autogenerated.
     */
    private void initComponents2() {
        sliders = new JSlider[]{jSlider1, jSlider2, jSlider3, jSlider4, jSlider5};
        alg = 'n';

        jButtonReset.setText("Reinicia criteris");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        slidersToLabel = new HashMap<>();
        slidersToLabel.put(sliders[0], jLabel1);
        slidersToLabel.put(sliders[1], jLabel2);
        slidersToLabel.put(sliders[2], jLabel3);
        slidersToLabel.put(sliders[3], jLabel4);
        slidersToLabel.put(sliders[4], jLabel5);

        for (final JSlider s : sliders) {
            s.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent e) {
                    slidersToLabel.get(s).setText(String.valueOf(s.getValue()));
                }
            });
        }
        jLabelErrMessage.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelRight = new javax.swing.JPanel();
        jPanelAlgorisme = new javax.swing.JPanel();
        jRadioButtonClique = new javax.swing.JRadioButton();
        jRadioButtonLouvain = new javax.swing.JRadioButton();
        jRadioButtonGirvan = new javax.swing.JRadioButton();
        jCercaButton = new javax.swing.JButton();
        jLabelErrMessage = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        PanelCriteri1 = new javax.swing.JPanel();
        nomCriteri1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        PanelCriteri2 = new javax.swing.JPanel();
        nomCriteri2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        PanelCriteri3 = new javax.swing.JPanel();
        nomCriteri3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        PanelCriteri4 = new javax.swing.JPanel();
        nomCriteri4 = new javax.swing.JLabel();
        jSlider4 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        PanelCriteri5 = new javax.swing.JPanel();
        nomCriteri5 = new javax.swing.JLabel();
        jSlider5 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonReset = new javax.swing.JButton();
        jButtonTornar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1152, 720));

        buttonGroup1.add(jRadioButtonClique);
        jRadioButtonClique.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jRadioButtonClique.setText("Clique");
        jRadioButtonClique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCliqueActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonLouvain);
        jRadioButtonLouvain.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jRadioButtonLouvain.setText("Louvain");
        jRadioButtonLouvain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLouvainActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonGirvan);
        jRadioButtonGirvan.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jRadioButtonGirvan.setText("Girvan-Newman");
        jRadioButtonGirvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGirvanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlgorismeLayout = new javax.swing.GroupLayout(jPanelAlgorisme);
        jPanelAlgorisme.setLayout(jPanelAlgorismeLayout);
        jPanelAlgorismeLayout.setHorizontalGroup(
                jPanelAlgorismeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAlgorismeLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanelAlgorismeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonLouvain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButtonGirvan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButtonClique, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanelAlgorismeLayout.setVerticalGroup(
                jPanelAlgorismeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAlgorismeLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jRadioButtonGirvan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jRadioButtonClique, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jRadioButtonLouvain, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jCercaButton.setText("Cerca");
        jCercaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCercaButtonActionPerformed(evt);
            }
        });

        jLabelErrMessage.setText("Missatge d'error");

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
                jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRightLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelAlgorisme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelRightLayout.createSequentialGroup()
                                                .addComponent(jLabelErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(jPanelRightLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jCercaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRightLayout.setVerticalGroup(
                jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRightLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jPanelAlgorisme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabelErrMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCercaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 30)); // NOI18N
        titleLabel.setText("Generar Solució");

        PanelCriteri1.setPreferredSize(new java.awt.Dimension(400, 70));

        nomCriteri1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        nomCriteri1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomCriteri1.setText("Similaritat Noms");
        nomCriteri1.setMaximumSize(new java.awt.Dimension(150, 22));
        nomCriteri1.setMinimumSize(new java.awt.Dimension(150, 22));
        nomCriteri1.setPreferredSize(new java.awt.Dimension(150, 22));

        jSlider1.setPaintLabels(true);
        jSlider1.setValue(20);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", Font.ITALIC, 16)); // NOI18N
        jLabel1.setText("20");

        javax.swing.GroupLayout PanelCriteri1Layout = new javax.swing.GroupLayout(PanelCriteri1);
        PanelCriteri1.setLayout(PanelCriteri1Layout);
        PanelCriteri1Layout.setHorizontalGroup(
                PanelCriteri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(nomCriteri1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap())
        );
        PanelCriteri1Layout.setVerticalGroup(
                PanelCriteri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelCriteri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomCriteri1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelCriteri1Layout.createSequentialGroup()
                                                .addGroup(PanelCriteri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 3, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        PanelCriteri2.setPreferredSize(new java.awt.Dimension(400, 70));

        nomCriteri2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        nomCriteri2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nomCriteri2.setText("Supercategories en comú");
        nomCriteri2.setMaximumSize(new java.awt.Dimension(150, 22));
        nomCriteri2.setMinimumSize(new java.awt.Dimension(150, 22));
        nomCriteri2.setPreferredSize(new java.awt.Dimension(150, 22));

        jSlider2.setValue(20);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", Font.ITALIC, 16)); // NOI18N
        jLabel2.setText("20");

        javax.swing.GroupLayout PanelCriteri2Layout = new javax.swing.GroupLayout(PanelCriteri2);
        PanelCriteri2.setLayout(PanelCriteri2Layout);
        PanelCriteri2Layout.setHorizontalGroup(
                PanelCriteri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(nomCriteri2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addContainerGap())
        );
        PanelCriteri2Layout.setVerticalGroup(
                PanelCriteri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelCriteri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomCriteri2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelCriteri2Layout.createSequentialGroup()
                                                .addGroup(PanelCriteri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 3, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        PanelCriteri3.setPreferredSize(new java.awt.Dimension(400, 70));

        nomCriteri3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        nomCriteri3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nomCriteri3.setText("Subcategories en comú");
        nomCriteri3.setMaximumSize(new java.awt.Dimension(150, 22));
        nomCriteri3.setMinimumSize(new java.awt.Dimension(150, 22));
        nomCriteri3.setPreferredSize(new java.awt.Dimension(150, 22));

        jSlider3.setValue(20);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", Font.ITALIC, 16)); // NOI18N
        jLabel3.setText("20");

        javax.swing.GroupLayout PanelCriteri3Layout = new javax.swing.GroupLayout(PanelCriteri3);
        PanelCriteri3.setLayout(PanelCriteri3Layout);
        PanelCriteri3Layout.setHorizontalGroup(
                PanelCriteri3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(nomCriteri3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addContainerGap())
        );
        PanelCriteri3Layout.setVerticalGroup(
                PanelCriteri3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCriteri3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelCriteri3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelCriteri3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel3))
                                        .addComponent(nomCriteri3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSlider3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15))
        );

        PanelCriteri4.setPreferredSize(new java.awt.Dimension(400, 70));

        nomCriteri4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        nomCriteri4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nomCriteri4.setText("Pàgines en comú");
        nomCriteri4.setMaximumSize(new java.awt.Dimension(150, 22));
        nomCriteri4.setMinimumSize(new java.awt.Dimension(150, 22));
        nomCriteri4.setPreferredSize(new java.awt.Dimension(150, 22));

        jSlider4.setValue(20);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", Font.ITALIC, 16)); // NOI18N
        jLabel4.setText("20");

        javax.swing.GroupLayout PanelCriteri4Layout = new javax.swing.GroupLayout(PanelCriteri4);
        PanelCriteri4.setLayout(PanelCriteri4Layout);
        PanelCriteri4Layout.setHorizontalGroup(
                PanelCriteri4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(nomCriteri4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addContainerGap())
        );
        PanelCriteri4Layout.setVerticalGroup(
                PanelCriteri4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelCriteri4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(nomCriteri4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSlider4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        PanelCriteri5.setPreferredSize(new java.awt.Dimension(400, 70));

        nomCriteri5.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        nomCriteri5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nomCriteri5.setText("Ser súper o subcategoria");
        nomCriteri5.setMaximumSize(new java.awt.Dimension(150, 22));
        nomCriteri5.setMinimumSize(new java.awt.Dimension(150, 22));
        nomCriteri5.setPreferredSize(new java.awt.Dimension(150, 22));

        jSlider5.setValue(20);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", Font.ITALIC, 16)); // NOI18N
        jLabel5.setText("20");

        javax.swing.GroupLayout PanelCriteri5Layout = new javax.swing.GroupLayout(PanelCriteri5);
        PanelCriteri5.setLayout(PanelCriteri5Layout);
        PanelCriteri5Layout.setHorizontalGroup(
                PanelCriteri5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(nomCriteri5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addContainerGap())
        );
        PanelCriteri5Layout.setVerticalGroup(
                PanelCriteri5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCriteri5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelCriteri5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomCriteri5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelCriteri5Layout.createSequentialGroup()
                                                .addGroup(PanelCriteri5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 3, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jButtonReset.setText("Reinicia criteris");

        jButtonTornar.setText("Tornar");
        jButtonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornarActionPerformed(evt);
            }
        });

        jLabel6.setText("Busca categories de la wikipedia similars entre elles segons els següents criteris. ");

        jLabel7.setText("Escull la importància que vols donar a cada criteri i l'algorisme que vols executar.");

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
                jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLeftLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jButtonTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelLeftLayout.createSequentialGroup()
                                                        .addGap(51, 51, 51)
                                                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(PanelCriteri1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                                                                .addComponent(PanelCriteri4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(PanelCriteri2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(PanelCriteri5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(PanelCriteri3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 564, Short.MAX_VALUE))
                        .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                                                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel6)
                                                                .addComponent(jLabel7))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addContainerGap())
                                                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                                                .addComponent(jButtonReset)
                                                .addGap(57, 57, 57))))
        );
        jPanelLeftLayout.setVerticalGroup(
                jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(PanelCriteri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelCriteri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelCriteri3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelCriteri4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelCriteri5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(jButtonTornar)
                                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JPanel PanelCriteri1;
    private javax.swing.JPanel PanelCriteri2;
    private javax.swing.JPanel PanelCriteri3;
    private javax.swing.JPanel PanelCriteri4;
    private javax.swing.JPanel PanelCriteri5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTornar;
    private javax.swing.JButton jCercaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelErrMessage;
    private javax.swing.JPanel jPanelAlgorisme;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JRadioButton jRadioButtonClique;
    private javax.swing.JRadioButton jRadioButtonGirvan;
    private javax.swing.JRadioButton jRadioButtonLouvain;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JLabel nomCriteri1;
    private javax.swing.JLabel nomCriteri2;
    private javax.swing.JLabel nomCriteri3;
    private javax.swing.JLabel nomCriteri4;
    private javax.swing.JLabel nomCriteri5;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration


    private JSlider[] sliders;
    private int NCriteris = 5;
    private char alg;
    private HashMap<JSlider, JLabel> slidersToLabel;
    private CalculatingView calculatingView;

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {
        for (JSlider s : sliders) s.setValue(20);
        for (JSlider s : sliders) s.setValue(20);
    }

    private void jRadioButtonCliqueActionPerformed(java.awt.event.ActionEvent evt) {
        alg = 'C';
    }

    private void jRadioButtonLouvainActionPerformed(java.awt.event.ActionEvent evt) {
        alg = 'L';
    }

    private void jRadioButtonGirvanActionPerformed(java.awt.event.ActionEvent evt) {
        alg = 'G';
    }


    private void jButtonTornarActionPerformed(java.awt.event.ActionEvent evt) {
        presentationController.synToMainView();
    }

    private void jCercaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (wikiCtrl == null) {
            JOptionPane.showMessageDialog(this, "No tens cap wikipedia carregada.", "Error", JOptionPane.CANCEL_OPTION);
            return;
        }
        jLabelErrMessage.setVisible(false);
        final ArrayList<Float> criteris = new ArrayList<>();

        int suma = 0;
        for (int i = 0; i < NCriteris; ++i) suma += sliders[i].getValue();
        float total = 0;
        for (int i = 0; i < NCriteris; ++i) {
            int v = sliders[i].getValue();
           // suma += v;
            if (i == NCriteris-1) criteris.add(100-total);
            else criteris.add((float) v*100/suma);
            total += criteris.get(i);
        }
        if (suma == 0) {
            JOptionPane.showMessageDialog(this, "Escull almenys un criteri.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (total != 100) {
            JOptionPane.showMessageDialog(this, "La suma de pesos ha de ser 100.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (presentationController.getWorking()) {
            JOptionPane.showMessageDialog(this, "Ja estàs cercant una solució.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (alg == 'n') {
            JOptionPane.showMessageDialog(this, "Selecciona algun algorisme!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {

            final SwingWorker worker = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    try {
                        calculatingView = new CalculatingView();
                        calculatingView.addWindowListener(new WindowListener() {
                            @Override
                            public void windowOpened(WindowEvent windowEvent) {
                            }

                            @Override
                            public void windowClosing(WindowEvent windowEvent) {
                                presentationController.setWorking(false);
                                cancel(true);
                            }

                            @Override
                            public void windowClosed(WindowEvent windowEvent) {
                                presentationController.setWorking(false);
                                cancel(true);
                            }

                            @Override
                            public void windowIconified(WindowEvent windowEvent) {
                            }

                            @Override
                            public void windowDeiconified(WindowEvent windowEvent) {
                            }

                            @Override
                            public void windowActivated(WindowEvent windowEvent) {
                            }

                            @Override
                            public void windowDeactivated(WindowEvent windowEvent) {
                            }
                        });
                        wikiCtrl.findSolution(alg, criteris);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error durant l'execució de l'algorisme!", "Error", JOptionPane.ERROR_MESSAGE);
                        calculatingView.close();
                        cancel(true);
                        e.printStackTrace();
                    }
                    return null;
                }

                @Override
                protected void done() {
                    jLabelErrMessage.setText("Finished.");
                    jLabelErrMessage.setVisible(false);
                    presentationController.setWorking(false);
                    if (!isCancelled()) {
                        GraphPanel.showWindow();
                        calculatingView.close();
                    }
                }
            };
            presentationController.setWorking(true);
            worker.execute();
        }
    }
}