package presentation;

import javax.swing.*;
import java.awt.*;

/**
 * Welcome panel, where the most general options are listed.
 * @author Pau Oliver
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        leftPanel = new javax.swing.JPanel();
        buttonGestionarWikipedia = new javax.swing.JButton();
        buttonGenerarSolucio = new javax.swing.JButton();
        buttonGestionarSolucio = new javax.swing.JButton();
        buttonEstadistiques = new javax.swing.JButton();
        buttonSortir = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        buttonAjuda = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1152, 720));
        setPreferredSize(new java.awt.Dimension(1152, 720));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGestionarWikipedia.setFont(new java.awt.Font("Loma", 0, 26)); // NOI18N
        buttonGestionarWikipedia.setText("Gestionar Wikipedia");
        buttonGestionarWikipedia.setMinimumSize(new java.awt.Dimension(300, 56));
        buttonGestionarWikipedia.setPreferredSize(new java.awt.Dimension(300, 60));
        buttonGestionarWikipedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionarWikipediaActionPerformed(evt);
            }
        });

        buttonGenerarSolucio.setFont(new java.awt.Font("Loma", 0, 26)); // NOI18N
        buttonGenerarSolucio.setText("Generar Solució");
        buttonGenerarSolucio.setMinimumSize(new java.awt.Dimension(300, 56));
        buttonGenerarSolucio.setPreferredSize(new java.awt.Dimension(300, 60));
        buttonGenerarSolucio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarSolucioActionPerformed(evt);
            }
        });

        buttonGestionarSolucio.setFont(new java.awt.Font("Loma", 0, 26)); // NOI18N
        buttonGestionarSolucio.setText("Gestionar Solucions");
        buttonGestionarSolucio.setMinimumSize(new java.awt.Dimension(300, 56));
        buttonGestionarSolucio.setPreferredSize(new java.awt.Dimension(300, 60));
        buttonGestionarSolucio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionarSolucioActionPerformed(evt);
            }
        });

        buttonEstadistiques.setFont(new java.awt.Font("Loma", 0, 26)); // NOI18N
        buttonEstadistiques.setText("Estadístiques");
        buttonEstadistiques.setMinimumSize(new java.awt.Dimension(300, 56));
        buttonEstadistiques.setPreferredSize(new java.awt.Dimension(300, 60));
        buttonEstadistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEstadistiquesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
                leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leftPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonGestionarWikipedia, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonGenerarSolucio, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonGestionarSolucio, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonEstadistiques, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(159, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
                leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leftPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(buttonGestionarWikipedia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(buttonGenerarSolucio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(buttonGestionarSolucio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(buttonEstadistiques, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(81, Short.MAX_VALUE))
        );

        buttonSortir.setText("Sortir");
        buttonSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortirActionPerformed(evt);
            }
        });

        headerPanel.setPreferredSize(new java.awt.Dimension(166, 47));

        headerLabel.setFont(new java.awt.Font("Liberation Serif", 0, 40)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Wikipedia");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        buttonAjuda.setText("Ajuda");
        buttonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
                rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 518, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
                rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(buttonAjuda)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(buttonSortir))
                                                        .addComponent(rightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jSeparator1))
                                .addGap(38, 38, 38))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(leftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(buttonSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35)))
                                .addGap(46, 46, 46))
        );
    }// </editor-fold>

    private void buttonGestionarWikipediaActionPerformed(java.awt.event.ActionEvent evt) {
        presentationController.synToWikipediaManagementView();
    }

    private void buttonGenerarSolucioActionPerformed(java.awt.event.ActionEvent evt) {
        presentationController.synToSearchPanel();
    }

    private void buttonGestionarSolucioActionPerformed(java.awt.event.ActionEvent evt) {
        presentationController.synToConsultSolutionView();
    }

    private void buttonEstadistiquesActionPerformed(java.awt.event.ActionEvent evt) {
        presentationController.synToStatisticsView();
    }

    private void buttonSortirActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void buttonAjudaActionPerformed(java.awt.event.ActionEvent evt) {
        presentationController.synToHelpView();
    }
    // Variables declaration - do not modify
    private javax.swing.JButton buttonAjuda;
    private javax.swing.JButton buttonEstadistiques;
    private javax.swing.JButton buttonGenerarSolucio;
    private javax.swing.JButton buttonGestionarSolucio;
    private javax.swing.JButton buttonGestionarWikipedia;
    private javax.swing.JButton buttonSortir;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration
    private PresentationController presentationController;

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel(PresentationController presentationController) {
        initComponents();
        this.presentationController = presentationController;
        initComponents2();
    }

    private void initComponents2() {
        headerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 30, 30));
        headerLabel = new JLabel(new ImageIcon("header.png"));
        //headerLabel.setIconTextGap(0);
        headerLabel.setVerticalAlignment(SwingConstants.TOP);
        headerLabel.setHorizontalAlignment(SwingConstants.CENTER);
        headerPanel.remove(0);
        headerPanel.add(headerLabel);

        add(headerPanel);

        rightPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 70, 20));
        JLabel label = new JLabel(new ImageIcon("logo.png"));
        label.setHorizontalAlignment(SwingConstants.LEFT);
        label.setVerticalAlignment(SwingConstants.TOP);
        rightPanel.add(label);
        add(rightPanel);
    }
}
